
##########################################################
#
#                    COMMON INFO
#
##########################################################

# ipfs api url

ipfs = "localhost:5001"

# Blog title
title           = "Alice's Blog"
# Blog description
description     = "happy hacking, happy ganking"
# author name
author          = "Alice"

##########################################################
#
#                     DIRECTORY
#
##########################################################

[dir]
# source directory
source          = "./source"

# source posts directory
posts           = "./source/posts"

# pulic directory
public         = "./public"

# theme
theme          = "./theme/default"