###
# ____             _ _ _
#|  _ \ __ _ _ __ (_) | | ___  _ __
#| |_) / _` | '_ \| | | |/ _ \| '_ \
#|  __/ (_| | |_) | | | | (_) | | | |
#|_|   \__,_| .__/|_|_|_|\___/|_| |_|
#           |_|
#
##########################################################
#
#                    COMMON INFO
#
##########################################################

# ipfs api url

ipfs = "localhost:5001"

# Blog title
title           = "Papillon's Blog"
# Blog description
description     = "Happy hacking, happy ganking"
# author name
author          = "Papillon"

##########################################################
#
#                     DIRECTORY
#
##########################################################

[dir]
# source directory
source          = "./source"

# source posts directory
posts           = "./source/posts"

# pulic directory
public         = "./public"

# theme
theme          = "./theme/default"