
##########################################################
#
#                    COMMON INFO
#
##########################################################

# Blog title
title           = "Alice's Blog"
# Blog description
description     = "happy hacking, happy ganking"
# author name
author          = "Alice"

##########################################################
#
#                     DIRECTORY
#
##########################################################

[dir]
# source directory
source          = "./blog/source"

# source posts directory
posts           = "./blog/source/posts"

# pulic directory
public         = "./blog/public"

# theme
theme          = "./blog/source/theme/default"



